pipeline:
  name: pipe2
  identifier: pipe2
  projectIdentifier: git_final_test2
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: CI
        identifier: CI
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.CItestK8sConnectorism97ViytL
              namespace: harness-qa-delegate
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: run
                  identifier: run
                  spec:
                    connectorRef: account.CItestDockerConnectorM75xpPYBMm
                    image: alpine
                    shell: Sh
                    command: echo run
  properties:
    ci:
      codebase:
        connectorRef: github
        build: <+input>
