pipeline:
  name: pipe
  identifier: pipe
  projectIdentifier: git_sync_test
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: github
        build: <+input>
  stages:
    - stage:
        name: ci
        identifier: ci
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.CItestK8sConnectorism97ViytL
              namespace: harness-qa-delegate
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: docker
                  identifier: docker
                  spec:
                    connectorRef: account.CItestDockerConnectorM75xpPYBMm
                    image: alpine
                    shell: Sh
                    command: echo run
